### ISSUE TITLE
### Issue: Unable to create a new user

### ISSUE THREAD

**Issue by ehinson69** [treehouse-apprenticeship/athena_irv4#14]
#### Issue Description

Attempting to create a new user produces the following validation error on the server:

```javascript
{
    "message": "Validation Failed",
    "errors": [
        "Cast to String failed for value \"Promise { <pending> }\" at path \"password\""
    ]
}
```

**Steps to Reproduce**

* Using Postman, send a POST request to the REST API.
  * URL: `http://localhost:5000/api/users`
  * Body (as JSON):
  
```javascript
{
  "firstName": "John",
  "lastName": "Smith",
  "emailAddress": "john@smith.com",
  "password": "password"
}
```

* The REST API returns a response with a `400 Bad Request` HTTP status code, indicating that the request failed.
  * If the user had been successfully created, we should have received a response with a `201 Created` HTTP status code.

**Comment by bricarolina** [comment]
In users.js I had to change line 43, had to add an await to the password.

**Comment by ehinson69** [comment]
Await was added to the password. Issue is resolved.
