### ISSUE TITLE
### Issue: The heading on the "Create Course" page displays as "Create Workshop"

### ISSUE THREAD

**Issue by ehinson69** [treehouse-apprenticeship/athena_irv4#9]
#### Issue Description

Need to update the "Create Course" page header to display "Create Course" instead of "Create Workshop".

**Steps to Reproduce**

* Using the React client, click on the "Sign In" link displayed in the header to browse to the "Sign In" page.
* Sign in using Joe's user information.
  * Email Address: joe@smith.com
  * Password: joepassword
* From the Course List page (i.e. the "Home" page), click on the "New Course" card to browse to the Create Course page.
* Notice that the page heading displays as "Create Workshop".
  * The page heading should display as "Create Course".

**Comment by SBeaver0590** [comment]
fixed issue #9.

**Comment by bricarolina** [comment]
The header needed to be changed from Workshop to Course.
